config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "about", to: "about#index"

  get "password", to: "passwords#edit"
  patch "password", to: "passwords#update", as: :edit_password

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  
  delete "logout", to: "sessions#destroy"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  root to: "main#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address" }

end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def index
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    if session[:user_id]
      Current.user = User.find_by(id: session[:user_id])
    end
  end

  def require_user_logged_in!
    redirect_to sign_in_path, alert: "You must be signed in to do that." if Current.user.nil?
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
  end

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])

    if @user.present?
      # Send Email
      PasswordMailer.with(user: @user).reset.deliver_later
    end

    redirect_to root_path, notice: "If an account with that emails was found, we have send a link to reset your password."
  end

  def edit
    @user = User.find_signed!(params[:token], purpose: "password_reset")
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to sign_in_path, alert: "Your token has expired. Please try again."
  end

  def update
    @user = User.find_signed!(params[:token], purpose: "password_reset")
    if @user.update(password_params)
      redirect_to sign_in_path, notice: "Your password was reset successfully. Please sign in."
    else
      render :edit
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :require_user_logged_in!
  def edit
  end

  def update
    if Current.user.update(password_params)
      redirect_to root_path, notice: "Password updated!"
    else
      render :edit
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Successfully create account"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged in successfully"
    else
      flash[:alert] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About us</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SheduledTweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


  <%= render partial: "shared/navbar" %>

  <div class="container">
    <%= render partial: "shared/flash" %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex aling-items-center justify-content-center">
  <h1>Welcome to Sheduled tweets!</h1>
</div>

app/views/password_resets/edit.html.erb
<h1>Reset your password</h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |f| %>
  <div class="mb-3">
    <% if @user.errors.any? %>
      <div class="alert alert-danger">
        <% @user.errors.full_messages.each do |m| %>
          <div><%= m %></div>
        <% end %>
      </div>
    <% end %>

    <div class="mb-3">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control", placeholder: "password" %>
    </div>

    <div class="mb-3">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control", placeholder: "confirmation_password" %>
    </div>

    <div class="mb-3">
      <%= f.submit "Reset Password", class: "btn btn-primary " %>
    </div>

<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot your password?</h1>

<%= form_with url: password_reset_path do |f| %>
  <div class="mb-3">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control", placeholder: "steve@apple.com" %>
  </div>

  <div class="mb-3">
    <%= f.submit "Reset Password", class: "btn btn-primary " %>
  </div>

<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info mt-4">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-warning mt-4" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Navbar", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active"%>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link"%>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
          <li class="nav-item">
            <%= link_to Current.user.email, edit_password_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-outline-secondary" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", sign_up_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", sign_in_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>      
    </div>
  </div>
</nav>